"use client";

import Link from "next/link";
import { useState } from "react";
import { motion } from "framer-motion";
import {
  ArrowLeft,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  List,
  ListOrdered,
  Quote,
  Code,
  Download,
  MoreHorizontal,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { AnimatedAIChat } from "@/components/ui/legal-ai-chat";

const toolbarButtons = [
  { icon: Bold, label: "Bold" },
  { icon: Italic, label: "Italic" },
  { icon: Underline, label: "Underline" },
  null, // separator
  { icon: AlignLeft, label: "Align Left" },
  { icon: AlignCenter, label: "Align Center" },
  { icon: AlignRight, label: "Align Right" },
  null,
  { icon: List, label: "Bullet List" },
  { icon: ListOrdered, label: "Numbered List" },
  null,
  { icon: Quote, label: "Quote" },
  { icon: Code, label: "Code" },
];

export default function Workspace() {
  const [showExport, setShowExport] = useState(false);
  const [documentTitle, setDocumentTitle] = useState("GST Return — Q4 FY2025");
  const [documentContent, setDocumentContent] = useState(`Taxpayer Details

Legal Name: Meridian Corp Ltd.
GSTIN: 27AABCM1234R1Z5
Tax Period: October – December 2024 (Q4 FY2025)
Filing Type: GSTR-3B

1. Outward Supplies (Sales)

Total taxable turnover: ₹4,82,40,000
Exempt supplies: ₹18,60,000
Nil-rated supplies: ₹4,20,000
Total Output IGST: ₹62,80,000

2. Input Tax Credit (ITC)

ITC available (IGST): ₹41,20,000
ITC reversed: ₹2,40,000
Net ITC claimed: ₹38,80,000

3. Tax Payable

Net GST liability: ₹24,00,000
Late fee (if any): Nil
Interest: Nil

Generated by LegalAI · Document ID: DOC-20250408-GST-Q4`);

  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      {/* Top Bar */}
      <div className="h-14 border-b border-border flex items-center px-4 gap-4 bg-card/50">
        <Link href="/dashboard">
          <Button variant="ghost" size="sm" className="gap-2">
            <ArrowLeft className="w-4 h-4" />
            Back
          </Button>
        </Link>
        <div className="w-px h-6 bg-border" />
        <span className="font-medium text-sm flex-1 truncate">{documentTitle}</span>
        <div className="flex items-center gap-2">
          <span className="text-xs px-2 py-1 bg-muted rounded-full border border-border font-mono">
            PRJ-20250408-A3K1
          </span>
          <div className="relative">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setShowExport(!showExport)}
              className="gap-2"
            >
              <Download className="w-4 h-4" />
              Export
            </Button>
            {showExport && (
              <motion.div
                initial={{ opacity: 0, y: 5 }}
                animate={{ opacity: 1, y: 0 }}
                className="absolute top-full right-0 mt-2 bg-card border border-border rounded-lg p-1 min-w-[160px] z-50 shadow-lg"
              >
                <button className="w-full text-left px-3 py-2 text-sm rounded-md hover:bg-muted flex items-center gap-2">
                  📄 Export as PDF
                </button>
                <button className="w-full text-left px-3 py-2 text-sm rounded-md hover:bg-muted flex items-center gap-2">
                  📝 Export as DOCX
                </button>
                <button className="w-full text-left px-3 py-2 text-sm rounded-md hover:bg-muted flex items-center gap-2">
                  📋 Export as TXT
                </button>
              </motion.div>
            )}
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex overflow-hidden">
        {/* Chat Panel */}
        <div className="w-96 border-r border-border flex flex-col bg-card/30">
          <div className="px-4 py-3 border-b border-border">
            <h3 className="font-medium text-sm">AI Assistant</h3>
          </div>
          <div className="flex-1 overflow-hidden">
            <AnimatedAIChat />
          </div>
        </div>

        {/* Editor Panel */}
        <div className="flex-1 flex flex-col overflow-hidden">
          {/* Editor Toolbar */}
          <div className="h-12 border-b border-border flex items-center px-4 gap-1">
            {toolbarButtons.map((btn, i) =>
              btn === null ? (
                <div key={i} className="w-px h-5 bg-border mx-1" />
              ) : (
                <button
                  key={btn.label}
                  className="w-8 h-8 rounded-md flex items-center justify-center hover:bg-muted transition-colors"
                  title={btn.label}
                >
                  <btn.icon className="w-4 h-4" />
                </button>
              )
            )}
            <div className="flex-1" />
            <button className="w-8 h-8 rounded-md flex items-center justify-center hover:bg-muted transition-colors">
              <MoreHorizontal className="w-4 h-4" />
            </button>
          </div>

          {/* Editor Body */}
          <div className="flex-1 overflow-y-auto p-8">
            <div className="max-w-3xl mx-auto">
              <input
                type="text"
                value={documentTitle}
                onChange={(e) => setDocumentTitle(e.target.value)}
                className="text-3xl font-medium w-full outline-none mb-6 bg-transparent"
                placeholder="Document title..."
              />
              <textarea
                value={documentContent}
                onChange={(e) => setDocumentContent(e.target.value)}
                className="w-full h-[500px] text-sm leading-relaxed text-muted-foreground outline-none resize-none bg-transparent"
                placeholder="Start typing or use AI to generate content..."
              />
              <p className="text-xs text-muted-foreground mt-4">
                Generated by LegalAI · Document ID: DOC-20250408-GST-Q4
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
